# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6528f4f7db2f298b35860a18c9eec70e05ec3ce2862748faffbb4fb781a8e1cc56fb76d90114df0471c3b18edbb0cacf346ae65351504e6ad27bc139f05706fd

test:
  secret_key_base: 89b889d6c2d53ced6fd20e861240985c57cda56f964aae3e34af12eeab0f24ef2007f36ebe966ce9d516d980322bd72b5380b3fa301fd51caa111902d30446bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
